= CloudBees action: Register build artifacts

Use this action to register multiple artifact versions in CloudBees Unify from a workflow run.
The action accepts a JSON array of artifact metadata objects, allowing you to register multiple artifacts in a single step.

:tip-caption: :bulb:
TIP: When registering just one artifact version, you can use link:https://github.com/cloudbees-io/register-build-artifact[register-build-artifact] as an alternative to this action.

[NOTE]
====
Do not include the `register-build-artifacts` action for the same artifact version with any of the following actions, as the resulting run would register duplicate artifact entries to CloudBees Unify.

* link:https://github.com/cloudbees-io/ecr-promote-image[Promote an image in Amazon ECR]
* link:https://github.com/cloudbees-io/s3-upload-object[Store an object on Amazon S3] (if `send-artifact-info: true`)
* link:https://github.com/cloudbees-io/crane[Copy Docker images with Crane]
* link:https://github.com/cloudbees-io/helm-push[Push a Helm chart]
* link:https://github.com/cloudbees-io/jfrog-artifactory-promote-image[Promote an image from JFrog Artifactory]
* link:https://github.com/cloudbees-io/jfrog-artifactory-upload-file[Upload a file to JFrog Artifactory] (if `send-artifact-info: true`)
* link:https://github.com/cloudbees-io/kaniko[Build and publish Docker images with Kaniko]
====

== Inputs

[cols="20%a,20%a,10%a,50%a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `artifact-metadata`
| String (JSON)
| YES
| A JSON array of artifact metadata objects.
    Each object must include:

    * `name` — artifact name (**required**)
    * `version` — version (**required**)
    * `url` — artifact URL (**required**)
    * `digest` — digest (**optional**)
    * `labels` — JSON array of strings (**optional**)
    * `commit` — commit ID from the source repository where the artifact was built ^<<footnote,[1]>>^ (**optional**)
    * `repositoryUrl` — repository URL ^<<footnote,[1]>>^ (**optional**)
    * `ref` — branch or tag reference ^<<footnote,[1]>>^ (**optional**)
    * `componentId` — component identifier (**optional**)
    * `type` — type of artifact, e.g., `docker`, `helm`, `maven`, etc. This field is for display purposes only. (**optional**)
|===

[#footnote]
^[1]^ Unlike the link:https://github.com/cloudbees-io/register-build-artifact[register-build-artifact] action, by default this action does not associate the artifact version with the code commit associated with the workflow run in the workflow's repository/branch.
If you want to associate a commit with this artifact version, specify the commit, repository and branch to use.

== Outputs

[cols="2a,1a,3a",options="header"]
.Output details
|===
| Output name
| Data type
| Description

| `artifact-ids`
| JSON string
| The output is a JSON object mapping each artifact's `url` to its unique artifact ID.
|===


== Usage examples

.Single artifact example
[source,yaml]
----
jobs:
  register_build_artifacts:
    steps:
      - name: Register Build Artifacts
        uses: cloudbees-io/register-build-artifacts@main
        id: register
        with:
          artifact-metadata: |
            [
              {
                "name": "myApp",
                "version": "1.0.0",
                "url": "docker.io/myapp/myimg:1.0.0",
                "type": "docker"
              }
            ]
----

.Multiple artifacts example
[source,yaml]
----
jobs:
  register_build_artifacts:
    steps:
      - name: Register Build Artifacts
        uses: cloudbees-io/register-build-artifacts@main
        id: register
        with:
          artifact-metadata: |
            [
              {
                "name": "myApp",
                "version": "1.0.0",
                "url": "docker.io/myapp/myimg:1.0.0",
                "type": "docker"
              },
              {
                "name": "myService",
                "url": "docker.io/myorg/myservice:2.3.4",
                "version": "2.3.4",
                "labels": [
                  "api",
                  "custom, label",
                  "\"custom label\"",
                  "backend:v1"
                ],
                "repositoryUrl": "https://github.com/example/myservice.git",
                "commitId": "789xyz654wvu",
                "ref": "refs/tags/v2.3.4",
                "digest": "sha256:abcdef1234567890",
                "componentId": "fa0592f9-88f8-4f5d-9f37-580a93ba55ce",
                "type": "docker"
              }
            ]
----

.Using output parameters
[source,yaml]
----
- name: Register artifacts 2
  id: register
  uses: cloudbees-io/register-build-artifacts@main
  with:
    artifact-metadata: |
      [
        {
          "name": "myApp2",
          "version": "1.0.02",
          "url": "docker.io/myapp/myimg:1.0.02"
        }
      ]
- name: Print output parameter artifact IDs
  uses: docker://alpine:latest
  shell: sh
  run: |
    echo "Artifact IDs: ${{ steps.register.outputs.artifact-ids }}"
----

== License

This code is made available under the
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[CloudBees Unify].
